### PR TITLE
Add new landingport images.

### PR DESCRIPTION
**Pull request by V-ktor**
Add .blend files of three new landingport images.

### CODE REVIEW

**Comment by bobbens** [comment]
Shouldn't the za'lek station be a station and not just a landing port?

**Comment by bobbens** [comment]
Oh, and could you also render the files and do a PR to https://github.com/naev/naev-artwork-production ? Thanks!

**Comment by V-ktor** [comment]
> Shouldn't the za'lek station be a station and not just a landing port?
I added alternative cameras for those renders, but nothing else was changed (except setting the background to transparent). The file is rather large so should there really be a copy of the file?

**Comment by UncombedCoconut** [comment]
Thanks! Rather than a copy of the file, I think we'd want a script that can remind us how to render the target assets from the source scenes.

**Pull request merged**
